export type GraphEntityType =
  | "order"
  | "delivery"
  | "invoice"
  | "payment"
  | "customer"
  | "product";

export type GraphEntity = {
  type: GraphEntityType;
  id: string;
};

/**
 * Must match the node IDs generated by `lib/graph.ts` getGraphData().
 */
export function toGraphNodeId(entity: GraphEntity): string {
  switch (entity.type) {
    case "order":
      return `order:${entity.id}`;
    case "delivery":
      return `delivery:${entity.id}`;
    case "invoice":
      return `invoice:${entity.id}`;
    case "payment":
      return `payment:${entity.id}`;
    case "customer":
      return `customer:${entity.id}`;
    case "product":
      return `product:${entity.id}`;
    default:
      return `unknown:${entity.id}`;
  }
}

